using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
namespace FastDBEngineGenerator
{
    partial class MainFormFix
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new Container();
            this.panel1 = new Panel();
            this.cboConnectionString = new ComboBox();
            this.btnConnect = new Button();
            this.label1 = new Label();
            this.panel2 = new Panel();
            this.splitter2 = new Splitter();
            this.panel5 = new Panel();
            this.linkLabel1 = new LinkLabel();
            this.splitter1 = new Splitter();
            this.panel3 = new Panel();
            this.treeView1 = new TreeView();
            this.imageList_0 = new ImageList(this.components);
            this.panel4 = new Panel();
            this.contextMenuStrip5 = new ContextMenuStrip(this.components);
            this.显示隐藏代码窗口ToolStripMenuItem = new ToolStripMenuItem();
            this.label2 = new Label();
            this.contextMenuStrip1 = new ContextMenuStrip(this.components);
            this.menuCopySpName = new ToolStripMenuItem();
            this.toolStripMenuItem1 = new ToolStripSeparator();
            this.menuGetXmlCommandBySP = new ToolStripMenuItem();
            this.contextMenuStrip2 = new ContextMenuStrip(this.components);
            this.menuCopyTableName = new ToolStripMenuItem();
            this.toolStripMenuItem2 = new ToolStripSeparator();
            this.生成增删改命令到剪切板ToolStripMenuItem = new ToolStripMenuItem();
            this.contextMenuStrip3 = new ContextMenuStrip(this.components);
            this.menuCopyDbName = new ToolStripMenuItem();
            this.名称ToolStripMenuItem = new ToolStripSeparator();
            this.根据查询生成数据实体类ToolStripMenuItem = new ToolStripMenuItem();
            this.toolStripMenuItem3 = new ToolStripSeparator();
            this.定位到指定对象ToolStripMenuItem = new ToolStripMenuItem();
            this.contextMenuStrip4 = new ContextMenuStrip(this.components);
            this.menuCopyViewName = new ToolStripMenuItem();
            this.txtSqlScript = new SyntaxHighlighterControlFix();
            this.txtCsCode = new SyntaxHighlighterControlFix();
            this.ucParameterStyle1 = new ucParameterStyleFix();
            this.ucCsClassStyle1 = new UcCsClassStyleFix();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.panel5.SuspendLayout();
            this.panel3.SuspendLayout();
            this.panel4.SuspendLayout();
            this.contextMenuStrip5.SuspendLayout();
            this.contextMenuStrip1.SuspendLayout();
            this.contextMenuStrip2.SuspendLayout();
            this.contextMenuStrip3.SuspendLayout();
            this.contextMenuStrip4.SuspendLayout();
            base.SuspendLayout();
            this.panel1.Controls.Add(this.cboConnectionString);
            this.panel1.Controls.Add(this.btnConnect);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Dock = DockStyle.Top;
            this.panel1.Location = new Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(0x38f, 0x24);
            this.panel1.TabIndex = 0;
            this.cboConnectionString.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.cboConnectionString.Font = new Font("Courier New", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cboConnectionString.FormattingEnabled = true;
            this.cboConnectionString.Location = new Point(0x4d, 7);
            this.cboConnectionString.Name = "cboConnectionString";
            this.cboConnectionString.Size = new Size(0x2ca, 0x17);
            this.cboConnectionString.TabIndex = 2;
            this.btnConnect.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.btnConnect.FlatStyle = FlatStyle.Popup;
            this.btnConnect.Location = new Point(0x328, 8);
            this.btnConnect.Name = "btnConnect";
            this.btnConnect.Size = new Size(0x5e, 0x15);
            this.btnConnect.TabIndex = 0;
            this.btnConnect.Text = "连接数据库(&C)";
            this.btnConnect.UseVisualStyleBackColor = true;
            this.btnConnect.Click += new EventHandler(this.btnConnect_Click);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(4, 11);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x41, 12);
            this.label1.TabIndex = 1;
            this.label1.Text = "连接字符串";
            this.panel2.Controls.Add(this.txtSqlScript);
            this.panel2.Controls.Add(this.splitter2);
            this.panel2.Controls.Add(this.txtCsCode);
            this.panel2.Controls.Add(this.panel5);
            this.panel2.Controls.Add(this.splitter1);
            this.panel2.Controls.Add(this.panel3);
            this.panel2.Dock = DockStyle.Fill;
            this.panel2.Location = new Point(0, 0x24);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(0x38f, 0x221);
            this.panel2.TabIndex = 1;
            this.splitter2.Dock = DockStyle.Top;
            this.splitter2.Location = new Point(0xe1, 0x18a);
            this.splitter2.Name = "splitter2";
            this.splitter2.Size = new Size(0x2ae, 7);
            this.splitter2.TabIndex = 4;
            this.splitter2.TabStop = false;
            this.panel5.Controls.Add(this.ucParameterStyle1);
            this.panel5.Controls.Add(this.ucCsClassStyle1);
            this.panel5.Controls.Add(this.linkLabel1);
            this.panel5.Dock = DockStyle.Top;
            this.panel5.Location = new Point(0xe1, 0);
            this.panel5.Name = "panel5";
            this.panel5.Size = new Size(0x2ae, 0x1a);
            this.panel5.TabIndex = 2;
            this.linkLabel1.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            //this.linkLabel1.Image = Resources.Help;
            this.linkLabel1.ImageAlign = ContentAlignment.MiddleLeft;
            this.linkLabel1.LinkBehavior = LinkBehavior.NeverUnderline;
            this.linkLabel1.Location = new Point(0x24b, 4);
            this.linkLabel1.Name = "linkLabel1";
            this.linkLabel1.Size = new Size(0x60, 0x11);
            this.linkLabel1.TabIndex = 7;
            this.linkLabel1.TabStop = true;
            this.linkLabel1.Text = "查看帮助页面";
            this.linkLabel1.TextAlign = ContentAlignment.MiddleRight;
            this.linkLabel1.LinkClicked += new LinkLabelLinkClickedEventHandler(this.linkLabel1_LinkClicked);
            this.splitter1.Location = new Point(0xdb, 0);
            this.splitter1.Name = "splitter1";
            this.splitter1.Size = new Size(6, 0x221);
            this.splitter1.TabIndex = 1;
            this.splitter1.TabStop = false;
            this.panel3.Controls.Add(this.treeView1);
            this.panel3.Controls.Add(this.panel4);
            this.panel3.Dock = DockStyle.Left;
            this.panel3.Location = new Point(0, 0);
            this.panel3.Name = "panel3";
            this.panel3.Size = new Size(0xdb, 0x221);
            this.panel3.TabIndex = 0;
            this.treeView1.Dock = DockStyle.Fill;
            this.treeView1.HideSelection = false;
            this.treeView1.ImageIndex = 0;
            this.treeView1.ImageList = this.imageList_0;
            this.treeView1.Location = new Point(0, 0x1a);
            this.treeView1.Name = "treeView1";
            this.treeView1.SelectedImageIndex = 0;
            this.treeView1.Size = new Size(0xdb, 0x207);
            this.treeView1.TabIndex = 1;
            this.treeView1.AfterCollapse += new TreeViewEventHandler(this.treeView1_AfterCollapse);
            this.treeView1.BeforeExpand += new TreeViewCancelEventHandler(this.treeView1_BeforeExpand);
            this.treeView1.AfterSelect += new TreeViewEventHandler(this.treeView1_AfterSelect);
            this.treeView1.NodeMouseClick += new TreeNodeMouseClickEventHandler(this.treeView1_NodeMouseClick);
            this.treeView1.KeyDown += new KeyEventHandler(this.treeView1_KeyDown);
            this.treeView1.AfterExpand += new TreeViewEventHandler(this.treeView1_AfterExpand);
            this.imageList_0.ColorDepth = ColorDepth.Depth8Bit;
            this.imageList_0.ImageSize = new Size(0x10, 0x10);
            this.imageList_0.TransparentColor = Color.Transparent;
            this.panel4.ContextMenuStrip = this.contextMenuStrip5;
            this.panel4.Controls.Add(this.label2);
            this.panel4.Dock = DockStyle.Top;
            this.panel4.Location = new Point(0, 0);
            this.panel4.Name = "panel4";
            this.panel4.Size = new Size(0xdb, 0x1a);
            this.panel4.TabIndex = 0;
            this.contextMenuStrip5.Items.AddRange(new ToolStripItem[] { this.显示隐藏代码窗口ToolStripMenuItem });
            this.contextMenuStrip5.Name = "contextMenuStrip5";
            this.contextMenuStrip5.Size = new Size(0x99, 0x30);
            this.显示隐藏代码窗口ToolStripMenuItem.Name = "显示隐藏代码窗口ToolStripMenuItem";
            this.显示隐藏代码窗口ToolStripMenuItem.Size = new Size(0x98, 0x16);
            this.显示隐藏代码窗口ToolStripMenuItem.Text = "隐藏 代码窗口";
            this.显示隐藏代码窗口ToolStripMenuItem.Click += new EventHandler(this.显示隐藏代码窗口ToolStripMenuItem_Click);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(4, 6);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x53, 12);
            this.label2.TabIndex = 0;
            this.label2.Text = "数据表列表(&D)";
            this.contextMenuStrip1.Items.AddRange(new ToolStripItem[] { this.menuCopySpName, this.toolStripMenuItem1, this.menuGetXmlCommandBySP });
            this.contextMenuStrip1.Name = "contextMenuStrip1";
            this.contextMenuStrip1.Size = new Size(210, 0x36);
            this.menuCopySpName.Name = "menuCopySpName";
            this.menuCopySpName.Size = new Size(0xd1, 0x16);
            this.menuCopySpName.Text = "复制名称";
            this.menuCopySpName.Click += new EventHandler(this.menuCopyViewName_Click);
            this.toolStripMenuItem1.Name = "toolStripMenuItem1";
            this.toolStripMenuItem1.Size = new Size(0xce, 6);
            this.menuGetXmlCommandBySP.Name = "menuGetXmlCommandBySP";
            this.menuGetXmlCommandBySP.Size = new Size(0xd1, 0x16);
            this.menuGetXmlCommandBySP.Text = "生成XmlCommand到剪切板";
            this.menuGetXmlCommandBySP.Click += new EventHandler(this.menuGetXmlCommandBySP_Click);
            this.contextMenuStrip2.Items.AddRange(new ToolStripItem[] { this.menuCopyTableName, this.toolStripMenuItem2, this.生成增删改命令到剪切板ToolStripMenuItem });
            this.contextMenuStrip2.Name = "contextMenuStrip2";
            this.contextMenuStrip2.Size = new Size(0xf6, 0x36);
            this.menuCopyTableName.Name = "menuCopyTableName";
            this.menuCopyTableName.Size = new Size(0xf5, 0x16);
            this.menuCopyTableName.Text = "复制名称";
            this.menuCopyTableName.Click += new EventHandler(this.menuCopyViewName_Click);
            this.toolStripMenuItem2.Name = "toolStripMenuItem2";
            this.toolStripMenuItem2.Size = new Size(0xf2, 6);
            this.生成增删改命令到剪切板ToolStripMenuItem.Name = "生成增删改命令到剪切板ToolStripMenuItem";
            this.生成增删改命令到剪切板ToolStripMenuItem.Size = new Size(0xf5, 0x16);
            this.生成增删改命令到剪切板ToolStripMenuItem.Text = "生成增删改XmlCommand到剪切板";
            this.生成增删改命令到剪切板ToolStripMenuItem.Click += new EventHandler(this.生成增删改命令到剪切板ToolStripMenuItem_Click);
            this.contextMenuStrip3.Items.AddRange(new ToolStripItem[] { this.menuCopyDbName, this.名称ToolStripMenuItem, this.根据查询生成数据实体类ToolStripMenuItem, this.toolStripMenuItem3, this.定位到指定对象ToolStripMenuItem });
            this.contextMenuStrip3.Name = "contextMenuStrip3";
            this.contextMenuStrip3.Size = new Size(0xcf, 0x52);
            this.menuCopyDbName.Name = "menuCopyDbName";
            this.menuCopyDbName.Size = new Size(0xce, 0x16);
            this.menuCopyDbName.Text = "复制名称";
            this.menuCopyDbName.Click += new EventHandler(this.menuCopyViewName_Click);
            this.名称ToolStripMenuItem.Name = "名称ToolStripMenuItem";
            this.名称ToolStripMenuItem.Size = new Size(0xcb, 6);
            this.根据查询生成数据实体类ToolStripMenuItem.Name = "根据查询生成数据实体类ToolStripMenuItem";
            this.根据查询生成数据实体类ToolStripMenuItem.Size = new Size(0xce, 0x16);
            this.根据查询生成数据实体类ToolStripMenuItem.Text = "根据查询生成数据实体类";
            this.根据查询生成数据实体类ToolStripMenuItem.Click += new EventHandler(this.根据查询生成数据实体类ToolStripMenuItem_Click);
            this.toolStripMenuItem3.Name = "toolStripMenuItem3";
            this.toolStripMenuItem3.Size = new Size(0xcb, 6);
            this.定位到指定对象ToolStripMenuItem.Name = "定位到指定对象ToolStripMenuItem";
            this.定位到指定对象ToolStripMenuItem.Size = new Size(0xce, 0x16);
            this.定位到指定对象ToolStripMenuItem.Text = "定位到指定对象";
            this.定位到指定对象ToolStripMenuItem.Click += new EventHandler(this.定位到指定对象ToolStripMenuItem_Click);
            this.contextMenuStrip4.Items.AddRange(new ToolStripItem[] { this.menuCopyViewName });
            this.contextMenuStrip4.Name = "contextMenuStrip4";
            this.contextMenuStrip4.Size = new Size(0x7b, 0x1a);
            this.menuCopyViewName.Name = "menuCopyViewName";
            this.menuCopyViewName.Size = new Size(0x7a, 0x16);
            this.menuCopyViewName.Text = "复制名称";
            this.menuCopyViewName.Click += new EventHandler(this.menuCopyViewName_Click);
            this.txtSqlScript.Dock = DockStyle.Fill;
            this.txtSqlScript.Location = new Point(0xe1, 0x191);
            this.txtSqlScript.Name = "txtSqlScript";
            this.txtSqlScript.Size = new Size(0x2ae, 0x90);
            this.txtSqlScript.TabIndex = 6;
            this.txtCsCode.Dock = DockStyle.Top;
            this.txtCsCode.Font = new Font("Courier New", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtCsCode.SetLanguage("cs");
            this.txtCsCode.Location = new Point(0xe1, 0x1a);
            this.txtCsCode.Margin = new Padding(3, 4, 3, 4);
            this.txtCsCode.Name = "txtCsCode";
            this.txtCsCode.SetReadOnly(false);
            this.txtCsCode.Size = new Size(0x2ae, 0x170);
            this.txtCsCode.TabIndex = 5;
            this.ucParameterStyle1.Location = new Point(0x41, 0);
            this.ucParameterStyle1.Name = "ucParameterStyle1";
            this.ucParameterStyle1.Size = new Size(0x18d, 0x19);
            this.ucParameterStyle1.TabIndex = 9;
            this.ucParameterStyle1.Visible = false;
            this.ucParameterStyle1.AddDelegate(new EventHandler(this.OntreeViewAfterSelect));
            this.ucCsClassStyle1.Location = new Point(3, 0);
            this.ucCsClassStyle1.Name = "ucCsClassStyle1";
            this.ucCsClassStyle1.Size = new Size(0x1f6, 0x19);
            this.ucCsClassStyle1.TabIndex = 8;
            this.ucCsClassStyle1.Visible = false;
            this.ucCsClassStyle1.AddEvent(new EventHandler(this.OntreeViewAfterSelect));
            base.AutoScaleDimensions = new SizeF(6f, 12f);
//            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x38f, 0x245);
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.panel1);
            base.KeyPreview = true;
            this.MinimumSize = new Size(700, 400);
            base.Name = "MainForm";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FastDBEngine CodeGenerator for ORACLE";
            base.WindowState = FormWindowState.Maximized;
            base.Load += new EventHandler(this.MainForm_Load);
            base.Shown += new EventHandler(this.MainForm_Shown);
            base.FormClosing += new FormClosingEventHandler(this.MainForm_FormClosing);
            base.KeyDown += new KeyEventHandler(this.MainForm_KeyDown);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel5.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.panel4.ResumeLayout(false);
            this.panel4.PerformLayout();
            this.contextMenuStrip5.ResumeLayout(false);
            this.contextMenuStrip1.ResumeLayout(false);
            this.contextMenuStrip2.ResumeLayout(false);
            this.contextMenuStrip3.ResumeLayout(false);
            this.contextMenuStrip4.ResumeLayout(false);
            base.ResumeLayout(false);
        }

        #endregion

        private Button btnConnect;
        private ComboBox cboConnectionString;
        private ContextMenuStrip contextMenuStrip1;
        private ContextMenuStrip contextMenuStrip2;
        private ContextMenuStrip contextMenuStrip3;
        private ContextMenuStrip contextMenuStrip4;
        private ContextMenuStrip contextMenuStrip5;
   //     private IContainer icontainer_0 = null;
        private ImageList imageList_0;
        private static readonly int int_0 = 0;
        private static readonly int int_1 = 1;
        private static readonly int int_2 = 2;
        private static readonly int int_3 = 3;
        private static readonly int int_4 = 4;
        private static readonly int int_5 = 5;
        private static readonly int int_6 = 6;
        private Label label1;
        private Label label2;
        private LinkLabel linkLabel1;
        private ToolStripMenuItem menuCopyDbName;
        private ToolStripMenuItem menuCopySpName;
        private ToolStripMenuItem menuCopyTableName;
        private ToolStripMenuItem menuCopyViewName;
        private ToolStripMenuItem menuGetXmlCommandBySP;
        private Panel panel1;
        private Panel panel2;
        private Panel panel3;
        private Panel panel4;
        private Panel panel5;
        private Splitter splitter1;
        private Splitter splitter2;
        private static readonly string str = "[None]";
        private static readonly string connText = Path.Combine(Path.GetDirectoryName(Application.ExecutablePath), "FastDBEngineGenerator.txt");
        private string conn;
        private static readonly string database = "DataBase";
        private static readonly string table = "Tables";
        private static readonly string views = "Views";
        private static readonly string Procedures = "Procedures";
        private ToolStripSeparator toolStripMenuItem1;
        private ToolStripSeparator toolStripMenuItem2;
        private ToolStripSeparator toolStripMenuItem3;
        private TreeNode treeNode_0;
        private TreeView treeView1;
        private SyntaxHighlighterControlFix txtCsCode;
        private SyntaxHighlighterControlFix txtSqlScript;
        private UcCsClassStyleFix ucCsClassStyle1;
        private ucParameterStyleFix ucParameterStyle1;
        private ToolStripMenuItem 定位到指定对象ToolStripMenuItem;
        private ToolStripMenuItem 根据查询生成数据实体类ToolStripMenuItem;
        private ToolStripSeparator 名称ToolStripMenuItem;
        private ToolStripMenuItem 生成增删改命令到剪切板ToolStripMenuItem;
        private ToolStripMenuItem 显示隐藏代码窗口ToolStripMenuItem;
    }
}