//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastDBEngineOracleDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBASIC_PRICE
    {
        public int PKID { get; set; }
        public string AREA { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string SPECTIFICATION_NAME { get; set; }
        public string MATERIAL_NAME { get; set; }
        public string FACTORY_NAME { get; set; }
        public Nullable<decimal> BASIC_PRICE { get; set; }
        public Nullable<int> TREND { get; set; }
        public Nullable<decimal> PERCENTAGE { get; set; }
        public Nullable<decimal> DIFFER_PRICE { get; set; }
        public Nullable<int> SORT_NO { get; set; }
        public Nullable<int> ADDED_BY { get; set; }
        public Nullable<System.DateTime> ADDED_TIME { get; set; }
        public Nullable<int> LAST_MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_TIME { get; set; }
        public string LAST_MODIFIED_IP { get; set; }
        public string VALID { get; set; }
    }
}
